import test from 'node:test';
import assert from 'node:assert/strict';
import {createContactHandler} from '../lib/contact-handler.ts';
const valid={name:'Test Example',email:'test@example.com',mobile:'+91 0000000000',company:'Example',title:'Engineer',inquiryType:'PCB Design',description:'Local automated test only.',botField:'',consent:true};
const request=(body,headers={})=>new Request('https://tatvix-engineering.priyanshukorat.chatgpt.site/api/contact',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:typeof body==='string'?body:JSON.stringify(body)});
test('rejects invalid fields and consent without contacting the delivery server',async()=>{let calls=0;const handler=createContactHandler(async()=>{calls++;throw Error('Must not deliver');});const r=await handler(request({...valid,email:'invalid',mobile:'',consent:false}));assert.equal(r.status,400);assert.deepEqual(Object.keys((await r.json()).errors).sort(),['consent','email','mobile']);assert.equal(calls,0);});
test('forwards only approved fields to the stable Tatvix origin and refuses redirects',async()=>{let captured;const handler=createContactHandler(async(url,options)=>{captured={url,options};return Response.json({success:true});});const r=await handler(request({...valid,unexpected:'discard'}));assert.equal(r.status,200);assert.equal((await r.json()).success,true);assert.equal(captured.url,'https://tatvix.netlify.app/api/contact');const sent=JSON.parse(captured.options.body);assert.equal(sent.email,valid.email);assert.equal(sent.unexpected,undefined);assert.equal(sent.consent,undefined);assert.equal(captured.options.method,'POST');assert.equal(captured.options.redirect,'manual');});
test('does not report success for delivery rejection, misleading 200 or network failure',async()=>{for(const deliver of [async()=>Response.json({success:false},{status:500}),async()=>Response.json({success:false}),async()=>{throw Error('offline');}]){const r=await createContactHandler(deliver)(request(valid));assert.equal(r.status,502);assert.equal((await r.json()).success,false);}});
test('rejects foreign origins, malformed JSON, oversized bodies and unexpected service types',async()=>{const handler=createContactHandler(async()=>{throw Error('Must not deliver');});assert.equal((await handler(request(valid,{Origin:'https://other.example'}))).status,403);assert.equal((await handler(request('{'))).status,400);assert.equal((await handler(request('x'.repeat(16001)))).status,413);assert.equal((await handler(request({...valid,inquiryType:'unknown'}))).status,400);});
test('honeypot blocks outbound mail and repeated requests are throttled',async()=>{let calls=0;const handler=createContactHandler(async()=>{calls++;return Response.json({success:true});});for(let i=0;i<5;i++)assert.equal((await handler(request({...valid,botField:'spam'}))).status,200);assert.equal((await handler(request(valid))).status,429);assert.equal(calls,0);});

test('prevents forwarding back to itself on the delivery origin',async()=>{let calls=0;const handler=createContactHandler(async()=>{calls++;return Response.json({success:true});});const r=await handler(new Request('https://tatvix.netlify.app/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(valid)}));assert.equal(r.status,503);assert.equal((await r.json()).success,false);assert.equal(calls,0);});
test('public www enquiries still reach the stable backend after a domain migration',async()=>{let calls=0;const handler=createContactHandler(async(url)=>{calls++;assert.equal(url,'https://tatvix.netlify.app/api/contact');return Response.json({success:true});});const r=await handler(new Request('https://www.tatvixtech.com/api/contact',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://www.tatvixtech.com'},body:JSON.stringify(valid)}));assert.equal(r.status,200);assert.equal(calls,1);});
test('upstream redirects do not become success or trigger another delivery',async()=>{let calls=0;const handler=createContactHandler(async()=>{calls++;return Response.redirect('https://www.tatvixtech.com/api/contact',307);});const r=await handler(request(valid));assert.equal(r.status,502);assert.equal((await r.json()).success,false);assert.equal(calls,1);});
