import ChapterExperience from '@/components/chapter-experience';
import {Plus,Wifi,Bluetooth,ArrowUpRight} from 'lucide-react';
import SiteFooter from '@/components/site-footer';
import CaseStudies from '@/components/case-studies';
const questions=[['Can you support one part of an existing product?','Yes. We can discuss a focused hardware, firmware, connectivity or application scope. We define the interfaces with the existing product before implementation.'],['What should we share to start?','Tell us the problem, product stage, intended users, key requirements and target timeline. We can then agree the next engineering steps and a suitable channel for technical files.'],['Are these real client products?','The interactive scenes are original engineering illustrations. They explain our disciplines and do not represent delivered client projects or measured product performance.'],['What deliverables will we receive?','Deliverables depend on the agreed scope. Hardware work may include schematics, layout and manufacturing files. Firmware and application work may include source, build outputs and documentation.']];
export default function Home(){return <>
<a className="skip" href="#main">Skip to content</a><ChapterExperience/>
<main id="main">
<section className="chapter intro" id="overview" data-world="0"><div className="intro-heading"><p className="kicker">Tatvix Technologies · Product engineering</p><h1>Ideas become<br/>extraordinary things.</h1></div><div className="intro-bottom"><p>Hardware, firmware and digital experiences.<br/>Engineered to work beautifully together.</p><a className="button" href="#hardware">Explore what we build</a></div><span className="scene-caption">From the first signal to the final experience.</span></section>
<section className="chapter hardware" id="hardware" data-world="1"><div className="chapter-heading"><p className="kicker">Hardware design</p><h2>Made real.<br/>Layer by layer.</h2></div><div className="chapter-copy"><p className="lead">Every connection starts<br/>with a considered decision.</p><p>We translate your requirements into circuit architecture, schematics and PCB layouts, considering components, interfaces, assembly and the environment your product will operate in.</p><ul className="deliverables"><li>Circuit architecture & schematics</li><li>PCB layout & component selection</li><li>BOM, Gerber & assembly outputs</li></ul></div><span className="scene-caption">Explore the physical foundation.</span></section>
<section className="chapter firmware" id="firmware" data-world="2"><div className="chapter-heading"><p className="kicker">Embedded systems</p><h2>The intelligence<br/>within.</h2></div><div className="chapter-copy"><p className="lead">A circuit becomes a system.</p><p>Firmware gives hardware its purpose. We bring device drivers, real-time logic and communication interfaces together around the requirements of your product.</p><ul className="deliverables"><li>Embedded C / C++ development</li><li>RTOS & device communication</li><li>Firmware integration & testing</li></ul></div><div className="scene-note">Input<span>Process</span>Respond</div></section>
<section className="chapter network" id="connectivity" data-world="3"><div className="chapter-heading"><p className="kicker">IoT & cloud integration</p><h2>One connection.<br/>A wider world.</h2><p>Sensors. Relays. Gateways. Connected to the cloud.</p><div className="protocol-legend"><span><Wifi size={18} aria-hidden="true"/>Wi-Fi</span><span><Bluetooth size={18} aria-hidden="true"/>BLE mesh</span><span>Device to app</span></div></div><div className="network-foot"><p>Connect devices to cloud services with wireless communication and data flows planned as part of the whole product.</p><ul className="deliverables"><li>BLE, Wi-Fi & wireless integration</li><li>MQTT & cloud communication</li><li>Device-to-application data flows</li></ul></div></section>
<section className="chapter applications" id="applications" data-world="4"><div className="chapter-heading"><p className="kicker">Web, mobile & custom software</p><h2>Technology.<br/>In human hands.</h2></div><div className="chapter-copy"><p className="lead">The interface is part of the product.</p><p>Make complex technology clear to the people using it. We build applications and dashboards that connect your product's capabilities to everyday tasks.</p><ul className="deliverables"><li>Web & mobile applications</li><li>Connected product dashboards</li><li>Custom software integration</li></ul></div><span className="scene-caption">Illustrative interface · Sample data</span></section>
<section className="chapter process" id="process" data-world="5"><div className="chapter-heading"><p className="kicker">How we work</p><h2>Considered at every step.</h2><p>Clear requirements. Connected decisions. A complete handover.</p></div><ol className="process-grid">{[['Discover','Understand the use case, operating conditions and constraints. Agree scope and expected outputs.'],['Design','Review architecture, interfaces and dependencies. Define how the system will be verified.'],['Integrate','Develop in focused iterations. Connect hardware, firmware, data and applications.'],['Verify','Check agreed requirements, resolve findings and prepare technical files and documentation.']].map(([title,text],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
<CaseStudies/><section className="reading-section company" id="company" data-world="6"><p className="kicker">Based in Ahmedabad, India</p><h2>The details matter.<br/>So does the whole.</h2><div className="company-copy"><p className="lead">A PCB, firmware and an application should feel like one product.</p><p>Tatvix Technologies brings hardware design, embedded systems, IoT and application development into one engineering conversation. Bring us the whole idea, or the part that needs solving.</p><a className="text-link" href="mailto:info@tatvixtech.com">Connect with our team</a></div></section>
<section className="reading-section faq" data-world="6"><h2>Good questions.<br/>Clear answers.</h2><div>{questions.map(([q,a])=><details key={q}><summary>{q}<Plus size={18} aria-hidden="true"/></summary><p>{a}</p></details>)}</div></section>
<section className="chapter contact contact-invitation" id="contact" data-world="6"><div className="contact-intro"><p className="kicker">Let's build what comes next.</p><h2>Your idea.<br/>Our next conversation.</h2><p className="contact-invitation-copy">Have a product in mind, or a question about our services? Share your requirements and connect with our engineering team.</p><a className="button project-cta" href="/contact">Discuss your project<ArrowUpRight size={19} aria-hidden="true"/></a><a className="contact-email" href="mailto:info@tatvixtech.com">info@tatvixtech.com</a></div></section>
</main><SiteFooter/></>}
