import DeviceExperience from "@/components/device-experience";
import { CircuitBoard, Cpu, Radio, MonitorSmartphone } from "lucide-react";
const services = [
 {name:"Hardware design", icon:CircuitBoard, text:"Schematics, PCB layouts, component selection, and manufacturing files for your product.", detail:"Schematics / PCB layout / BOM"},
 {name:"Embedded firmware", icon:Cpu, text:"The intelligence inside your device. Embedded software built around your hardware and interfaces.", detail:"C & C++ / RTOS / Device interfaces"},
 {name:"IoT & connectivity", icon:Radio, text:"Connect physical products to useful data through wireless communication and cloud integration.", detail:"BLE & Wi-Fi / MQTT / Cloud integration"},
 {name:"Web & mobile", icon:MonitorSmartphone, text:"Clear, practical applications that help people interact with connected systems.", detail:"Web applications / Mobile / Dashboards"}
];
export default function Home(){return <>
<a className="skip" href="#main">Skip to content</a>
<header className="header shell"><a href="/" className="brand" aria-label="Tatvix Technologies home">tatvix<span>technologies</span></a><nav aria-label="Main navigation"><a href="#expertise">Expertise</a><a href="#process">Our process</a><a href="#about">About</a></nav><details className="mobile-nav"><summary>Menu</summary><nav aria-label="Mobile navigation"><a href="#expertise">Expertise</a><a href="#process">Our process</a><a href="#about">About</a></nav></details><a className="button small" href="mailto:info@tatvixtech.com">Let’s talk</a></header>
<main id="main"><section className="hero shell"><div className="hero-copy"><p className="intro">Engineering ideas into connected products.</p><h1>Great products<br/>start beneath<br/>the surface.</h1><p className="lede">Hardware, firmware, and software.<br/>Thoughtfully engineered to work as one.</p><div className="actions"><a className="button" href="mailto:info@tatvixtech.com?subject=Discuss%20a%20project">Discuss your project</a><a className="text-link" href="#expertise">Explore our expertise</a></div></div><DeviceExperience/></section>
<div className="scope shell"><p>From the first circuit.<br/>To the connected experience.</p><div>Hardware <span>·</span> Firmware <span>·</span> IoT <span>·</span> Applications</div></div>
<section className="section shell" id="expertise"><div className="section-heading"><h2>Every layer.<br/>One engineering partner.</h2><p>Build a complete product, or bring us in where you need specialist support.</p></div><div className="service-grid">{services.map(({name,icon:Icon,text,detail})=><article key={name}><Icon size={28} aria-hidden="true"/><h3>{name}</h3><p>{text}</p><div className="detail">{detail}</div></article>)}</div></section>
<section className="about" id="about"><div className="shell about-grid"><p className="intro">Built around the whole product.</p><div><h2>Good engineering connects the details.</h2><p>A device is more than a circuit board. It is the firmware that makes it work, the connection that moves its data, and the application someone uses every day.</p><p>Tatvix Technologies brings hardware, embedded systems, IoT, and application development together. We begin with the problem your product needs to solve, then shape the engineering around it.</p><div className="signal"><span>Physical device</span><span>Embedded intelligence</span><span>Connected experience</span></div></div></div></section>
<section className="section shell" id="process"><div className="section-heading"><h2>A clear path<br/>from idea to implementation.</h2><p>Scope first. Build deliberately. Verify against the requirements.</p></div><ol className="process">{[["Define","Understand the use case, constraints, interfaces, and expected deliverables."],["Design","Plan the architecture and review the hardware and software decisions."],["Develop","Build prototypes and implement the systems in focused iterations."],["Verify","Test against agreed requirements and prepare the technical handover."]].map(([title,text],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
<section className="section shell questions"><h2>Before we start.</h2><div><details><summary>Can you help with only part of a product?</summary><p>Yes. Contact us about hardware design, embedded firmware, IoT connectivity, or application development. We will agree the scope and interfaces before work starts.</p></details><details><summary>What should I include in an enquiry?</summary><p>Tell us the problem you want to solve, the current stage of the product, key requirements, and your intended timeline. Share sensitive technical files only after agreeing an appropriate channel.</p></details><details><summary>Is the interactive device a client project?</summary><p>No. It is an illustrative device concept used to explain the layers of a connected product.</p></details></div></section>
<section className="contact shell"><div><p className="intro">Your next product starts with a conversation.</p><h2>Let’s make<br/>the idea work.</h2></div><div><a className="button" href="mailto:info@tatvixtech.com">info@tatvixtech.com</a><p>Tell us what you are building.<br/>We’ll discuss where we can help.</p></div></section></main><footer className="shell"><a className="brand" href="/">tatvix<span>technologies</span></a><p>Ahmedabad, Gujarat, India</p><p>© {new Date().getFullYear()} Tatvix Technologies</p></footer></>}
