'use client';
import {useEffect,useRef,useState} from 'react';
import {Pause,Play} from 'lucide-react';
import {buildEngineeringScenes} from './engineering-scenes';
const chapters=[['overview','Overview'],['hardware','Hardware'],['firmware','Firmware'],['connectivity','Connectivity'],['applications','Applications'],['process','Process']];
export default function ChapterExperience(){
 const host=useRef<HTMLDivElement>(null),control=useRef<((v:boolean)=>void)|null>(null);
 const [active,setActive]=useState(0),[paused,setPaused]=useState(false),[menu,setMenu]=useState(false),[ready,setReady]=useState(false);
 useEffect(()=>{if(!menu)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);document.querySelector<HTMLButtonElement>('.menu-toggle')?.focus();}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[menu]);
 useEffect(()=>{let dead=false,dispose=()=>{};
 async function init(){
 const [T,{RoundedBoxGeometry},{RoomEnvironment},{gsap}]=await Promise.all([import('three'),import('three/addons/geometries/RoundedBoxGeometry.js'),import('three/addons/environments/RoomEnvironment.js'),import('gsap')]);if(dead)return;
 const el=host.current!,renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setClearColor(0,0);renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<760?1.25:1.6));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,80);camera.position.set(0,0,13);
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.05);scene.environment=env.texture;scene.environmentIntensity=1.2;room.dispose();pmrem.dispose();
 scene.add(new T.HemisphereLight(0xc5e9ff,0x10111c,2.5));const key=new T.DirectionalLight(0xffffff,4);key.position.set(3,6,5);scene.add(key);const rim=new T.DirectionalLight(0x88cde8,4);rim.position.set(-5,2,-3);scene.add(rim);
 const materials:InstanceType<typeof T.Material>[]=[],textures:InstanceType<typeof T.Texture>[]=[];
 function mat(color:number,metalness=.7,roughness=.3,emissive=0){const m=new T.MeshStandardMaterial({color,metalness,roughness,emissive,emissiveIntensity:emissive?1.7:0,transparent:true});materials.push(m);return m;}
 const groups=Array.from({length:6},()=>{const g=new T.Group();scene.add(g);return g;});
 const box=(g:InstanceType<typeof T.Group>,w:number,h:number,d:number,x:number,y:number,z:number,m:InstanceType<typeof T.Material>,r=.05)=>{const o=new T.Mesh(new RoundedBoxGeometry(w,h,d,2,Math.min(r,w/3,h/3,d/3)),m);o.position.set(x,y,z);g.add(o);return o;};
 function line(g:InstanceType<typeof T.Group>,points:number[][],color:number,opacity=.5){const m=new T.LineBasicMaterial({color,transparent:true,opacity});materials.push(m);const o=new T.Line(new T.BufferGeometry().setFromPoints(points.map(p=>new T.Vector3(...p))),m);g.add(o);return o;}
 const metal=()=>mat(0xa9beca,.95,.2),dark=()=>mat(0x14232e,.75,.26),ice=()=>mat(0x9bdbe7,.45,.22,0x2a6578),copper=()=>mat(0xcc9368,.85,.3);
 // The opening is an abstract, flowing signal sculpture, not a recurring product device.
 const signal=groups[0],signalMat=mat(0x376779,.9,.3);const knot=new T.Mesh(new T.TorusKnotGeometry(1.35,.36,180,24,2,3),signalMat);signal.add(knot);knot.rotation.x=.5;
 for(let i=0;i<3;i++){const ring=new T.Mesh(new T.TorusGeometry(2.1+i*.24,.012,6,120),i===1?copper():ice());ring.rotation.set(.5+i*.8,.6+i*.6,.2);signal.add(ring);}
 // Application surfaces: original sample dashboard mapped onto true 3D screen objects.
 function screenTexture(mobile:boolean){const c=document.createElement('canvas');c.width=mobile?420:1000;c.height=mobile?800:640;const ctx=c.getContext('2d')!;ctx.fillStyle='#0b1722';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#e9f4f5';ctx.font=mobile?'bold 30px sans-serif':'bold 34px sans-serif';ctx.fillText('tatvix',32,55);ctx.fillStyle='#86c6d8';ctx.font='18px sans-serif';ctx.fillText('Connected workspace',32,90);ctx.fillStyle='#162b3b';ctx.fillRect(28,120,c.width-56,130);ctx.fillStyle='#bdccd4';ctx.font='18px sans-serif';ctx.fillText('System overview',48,155);ctx.fillStyle='#e7f1f4';ctx.font='bold 40px sans-serif';ctx.fillText('24.8 °C',48,215);ctx.font='15px sans-serif';ctx.fillStyle='#97d9ba';ctx.fillText('Sample sensor',mobile?220:440,212);ctx.strokeStyle='#8ed4e7';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<50;i++){const x=32+i*(c.width-64)/49,y=mobile?370:350;const yy=y-Math.sin(i*.27)*42-Math.sin(i*.71)*14;i?ctx.lineTo(x,yy):ctx.moveTo(x,yy);}ctx.stroke();ctx.font='17px sans-serif';ctx.fillStyle='#a5bac6';ctx.fillText('Recent activity',32,mobile?480:450);for(let i=0;i<3;i++){const y=(mobile?520:488)+i*43;ctx.fillStyle='#213b4b';ctx.fillRect(32,y,c.width-64,1);ctx.fillStyle='#c9d7de';ctx.fillText(['Device connected','Reading received','Settings updated'][i],32,y+28);}ctx.fillStyle='#688896';ctx.font='14px sans-serif';ctx.fillText('Illustrative interface · Sample data',32,c.height-28);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;textures.push(t);return t;}
 const apps=groups[4],caseMat=dark(),edgeMat=metal();const desktop=new T.Group();apps.add(desktop);box(desktop,4.45,2.92,.16,0,.2,0,caseMat,.09);const screenMat=new T.MeshBasicMaterial({map:screenTexture(false),transparent:true});materials.push(screenMat);const display=new T.Mesh(new T.PlaneGeometry(4.2,2.69),screenMat);display.position.set(0,.2,.095);desktop.add(display);box(desktop,.2,.9,.14,0,-1.65,-.04,edgeMat);box(desktop,1.6,.07,.9,0,-2.08,.05,edgeMat);desktop.rotation.y=-.15;
 const phone=new T.Group();apps.add(phone);phone.position.set(1.95,-.65,.9);phone.rotation.set(.05,-.3,-.1);box(phone,1.05,2.1,.13,0,0,0,edgeMat,.1);const phoneMat=new T.MeshBasicMaterial({map:screenTexture(true),transparent:true});materials.push(phoneMat);const phoneScreen=new T.Mesh(new T.PlaneGeometry(.96,1.91),phoneMat);phoneScreen.position.z=.077;phone.add(phoneScreen);box(phone,.28,.04,.018,0,.91,.092,caseMat,.01);
 const engineering=buildEngineeringScenes(T,RoundedBoxGeometry,groups,materials,textures);
 // Shared, restrained particle field keeps the scene changes connected.
 const positions=new Float32Array(180*3);for(let i=0;i<180;i++){positions[i*3]=Math.sin(i*12.9)*13;positions[i*3+1]=Math.cos(i*7.7)*7;positions[i*3+2]=-4-Math.abs(Math.sin(i))*5;}const pg=new T.BufferGeometry();pg.setAttribute('position',new T.BufferAttribute(positions,3));const pm=new T.PointsMaterial({color:0x88a8bd,size:.018,transparent:true,opacity:.38});materials.push(pm);const particles=new T.Points(pg,pm);scene.add(particles);
 const groupMats=groups.map(g=>{const entries=new Map<InstanceType<typeof T.Material>,number>();g.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line||o instanceof T.Sprite){const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>entries.set(m,m.opacity));}});return entries;});
 const pose=[{x:0,y:-2.25,s:.72,rx:.2,ry:.2},{x:-2.6,y:-1.45,s:1.15,rx:.85,ry:.18},{x:2.45,y:-1.3,s:1.06,rx:.75,ry:-.35},{x:0,y:-2.1,s:.95,rx:.32,ry:-.1},{x:-2.4,y:-1.25,s:.95,rx:.08,ry:.1},{x:0,y:-.8,s:1.06,rx:.38,ry:-.1}];
 const weights=groups.map((_,i)=>({v:i===0?1:0}));const reduced=matchMedia('(prefers-reduced-motion: reduce)');let current=0,paused=false,raf=0,last=0,clock=0,previous=0,px=0,py=0,targetX=0,targetY=0,scrollFrame=0;let sections=Array.from(document.querySelectorAll<HTMLElement>('[data-world]'));let activeSection=sections[0];const sceneSections=groups.map((_,i)=>sections.find(s=>Number(s.dataset.world)===i) || sections[0]);
 function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();update();draw();}
 function update(){scrollFrame=0;const anchor=innerHeight*.48;let section=sections[0];for(const s of sections){if(s.getBoundingClientRect().top<=anchor)section=s;}activeSection=section;const next=Number(section.dataset.world);if(next<6)sceneSections[next]=section;if(next!==current){current=next;setActive(next);weights.forEach((w,i)=>gsap.to(w,{v:i===next?1:0,duration:reduced.matches||paused?0:1.05,ease:'power2.inOut',overwrite:true,onUpdate:()=>{if(reduced.matches||paused)draw();}}));}if(reduced.matches||paused)draw();}
 function onScroll(){if(!scrollFrame)scrollFrame=requestAnimationFrame(update);}
 function draw(){const mobile=innerWidth<760;px+=(targetX-px)*.065;py+=(targetY-py)*.065;const t=clock;groups.forEach((g,i)=>{const w=weights[i].v;g.visible=w>.002;if(!g.visible)return;const p=pose[i];const section=sceneSections[i],sectionTop=section.getBoundingClientRect().top;let y=p.y-sectionTop/innerHeight*9,x=p.x,s=p.s;if(i===0&&!mobile){const heading=section.querySelector('.intro-heading');if(heading)y=(.5-(heading.getBoundingClientRect().bottom+145)/innerHeight)*9;}if(mobile){x=i===3?-.22:0;s=i===5?.43:i===3?.49:i===4?.59:i===0?.62:i===2?.64:.73;const heading=section.querySelector('.chapter-heading'),headingEnd=heading?heading.getBoundingClientRect().bottom-sectionTop:200;const pixel=sectionTop+(i===0?innerHeight*.59:headingEnd+175);y=(.5-pixel/innerHeight)*9;}
 g.position.set(x,y-(1-w)*.65,-(1-w)*1.5);g.scale.setScalar(s*(.88+.12*w));g.rotation.set(p.rx+py*.08,p.ry+px*.16,0);groupMats[i].forEach((alpha,m)=>m.opacity=alpha*w);});
 knot.rotation.y=t*.12;signal.rotation.z=Math.sin(t*.2)*.06;engineering.animate(t);phone.position.y=-.65+Math.sin(t*.6)*.05;particles.rotation.y=px*.015;renderer.render(scene,camera);}
 function tick(time:number){raf=0;if(dead||document.hidden)return;const interval=innerWidth<760?33:16;if(time-last>=interval){if(previous)clock+=Math.min((time-previous)/1000,.05);previous=time;draw();last=time;}if(!paused&&!reduced.matches)raf=requestAnimationFrame(tick);}
 function wake(){previous=0;if(!raf&&!document.hidden&&!paused&&!reduced.matches)raf=requestAnimationFrame(tick);else draw();}
 function move(e:PointerEvent){if(paused||reduced.matches||e.pointerType!=='mouse')return;targetX=e.clientX/innerWidth*2-1;targetY=e.clientY/innerHeight*2-1;}
 function visibility(){if(document.hidden){cancelAnimationFrame(raf);raf=0;}else wake();}
 function motion(){cancelAnimationFrame(raf);raf=0;if(reduced.matches){weights.forEach((w,i)=>{gsap.killTweensOf(w);w.v=i===current?1:0;});targetX=targetY=px=py=0;}wake();}
 control.current=(v)=>{paused=v;cancelAnimationFrame(raf);raf=0;if(v){weights.forEach((w,i)=>{gsap.killTweensOf(w);w.v=i===current?1:0;});targetX=targetY=px=py=0;}wake();};
 window.addEventListener('resize',resize);window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('pointermove',move,{passive:true});document.addEventListener('visibilitychange',visibility);reduced.addEventListener('change',motion);resize();setReady(true);wake();
 dispose=()=>{cancelAnimationFrame(raf);cancelAnimationFrame(scrollFrame);weights.forEach(w=>gsap.killTweensOf(w));window.removeEventListener('resize',resize);window.removeEventListener('scroll',onScroll);window.removeEventListener('pointermove',move);document.removeEventListener('visibilitychange',visibility);reduced.removeEventListener('change',motion);scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line||o instanceof T.Points)o.geometry.dispose();});materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());env.dispose();renderer.dispose();renderer.domElement.remove();control.current=null;};
 }
 init().catch(()=>setReady(false));return()=>{dead=true;dispose();};},[]);
 return <><div className="world-canvas" ref={host} aria-hidden="true"><div className="world-fallback"/></div><header className="site-header"><a href="#overview" className="wordmark" aria-label="Tatvix Technologies home">tatvix<span>technologies</span></a><nav className="chapter-nav" aria-label="Explore our expertise">{chapters.slice(1).map(([id,label],i)=><a key={id} href={'#'+id} aria-current={active===i+1?'true':undefined}>{label}</a>)}</nav><a className="header-contact" href="#contact">Let's talk</a>{ready&&<button className="motion-control" aria-label={paused?'Resume motion':'Pause motion'} title={paused?'Resume motion':'Pause motion'} aria-pressed={paused} onClick={()=>{control.current?.(!paused);setPaused(!paused);}}>{paused?<Play size={14}/>:<Pause size={14}/>}<span>{paused?'Resume motion':'Pause motion'}</span></button>}<button className="menu-toggle" aria-expanded={menu} aria-controls="chapter-menu" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button></header>{menu&&<nav className="menu-panel" id="chapter-menu" aria-label="Mobile navigation">{[...chapters,['company','Company'],['contact','Contact']].map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}</nav>}</>;
}
