import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {getPostBySlug,getAllPostsSorted,type BlogPost} from '@/content/published-case-studies';
import SiteFooter from '@/components/site-footer';
import CaseAtmosphere from '@/components/case-atmosphere';
import {pageMetadata,canonical} from '@/lib/seo';
type Props={params:Promise<{slug:string}>};
function ArticleData({post}:{post:BlogPost}){const data={'@context':'https://schema.org','@type':'Article',headline:post.title,description:post.description,datePublished:post.publishedAt,author:{'@type':'Organization',name:post.author},publisher:{'@id':canonical('/#organization'),'@type':'Organization',name:'Tatvix Technologies',url:canonical('/')},mainEntityOfPage:canonical('/case-studies/'+post.slug)};return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>;}
export function generateStaticParams(){return getAllPostsSorted().map(({slug})=>({slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const post=getPostBySlug(slug);return post?{...pageMetadata(post.title,post.description,'/case-studies/'+slug),openGraph:{...pageMetadata(post.title,post.description,'/case-studies/'+slug).openGraph,type:'article',publishedTime:post.publishedAt,authors:[post.author]}}:{};}
export default async function CaseStudy({params}:Props){const {slug}=await params;const post=getPostBySlug(slug);if(!post)notFound();return <div className="case-study-page"><a className="skip" href="#main">Skip to content</a><CaseAtmosphere/><header className="document-header"><a href="/#overview" className="wordmark">Tatvix<span>Technologies</span></a><a className="text-link" href="/contact">Let's talk</a></header><main id="main" className="case-document"><ArticleData post={post}/><a className="text-link" href="/#case-studies">All case studies</a><div className="case-document-intro"><p className="kicker">{post.tags[0]}</p><h1>{post.title}</h1><p className="lead">{post.description}</p><p className="document-note">{post.author} · {post.authorRole} · Published <time dateTime={post.publishedAt}>{post.publishedAt}</time></p></div><article className="legal-content">{post.sections.map((section,i)=>{switch(section.type){case 'p':return <p key={i}>{section.text}</p>;case 'h2':return <h2 key={i}>{section.text}</h2>;case 'h3':return <h3 key={i}>{section.text}</h3>;case 'ul':return <ul key={i}>{section.items.map(item=><li key={item}>{item}</li>)}</ul>;case 'blockquote':return <blockquote key={i}>{section.text}</blockquote>;default:return null;}})}</article><aside className="case-document-cta"><h2>Facing a similar challenge?</h2><a className="button" href="/contact">Tell us about your project</a></aside></main><SiteFooter/></div>}
