import {notFound} from 'next/navigation';
import {services} from '@/content/services';
import {industries} from '@/content/industries';
import {breadcrumbData,canonical,pageMetadata,site} from '@/lib/seo';
import StructuredData from '@/components/structured-data';
import ContentShell,{ProjectInvitation} from '@/components/content-shell';
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return services.map(({slug})=>({slug}));}
export async function generateMetadata({params}:Props){const {slug}=await params;const s=services.find(s=>s.slug===slug);return s?pageMetadata(s.name,s.summary,'/services/'+slug):{};}
export default async function ServicePage({params}:Props){const {slug}=await params;const s=services.find(s=>s.slug===slug);if(!s)notFound();const path='/services/'+slug;return <ContentShell><StructuredData data={breadcrumbData([{name:'Home',path:'/'},{name:'Services',path:'/services'},{name:s.name,path}])}/><StructuredData data={{'@context':'https://schema.org','@type':'Service',name:s.name,description:s.summary,url:canonical(path),provider:{'@id':canonical('/#organization'),name:site.name}}}/><nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/services">Services</a></nav><p className="kicker">Tatvix engineering</p><h1>{s.name}</h1><p className="knowledge-lead">{s.intro}</p><div className="knowledge-columns"><section><h2>What we work through</h2><ol className="scope-list">{s.work.map(t=><li key={t}>{t}</li>)}</ol></section><section><h2>Typical deliverables</h2><ul className="scope-list">{s.outputs.map(t=><li key={t}>{t}</li>)}</ul><p className="document-note">Final deliverables, acceptance criteria and responsibilities are defined in the agreed project scope.</p></section></div><section className="knowledge-section"><p className="kicker">Tools & technologies</p><h2>Selected for the requirements.</h2><p>Technology choices depend on your product. Relevant options include:</p><ul className="technology-list">{s.technologies.map(t=><li key={t}>{t}</li>)}</ul><p className="document-note">Technology names describe engineering options, not vendor partnerships or endorsements.</p></section><section className="knowledge-section"><h2>{s.question}</h2><p>{s.answer}</p></section><section className="knowledge-section"><h2>Explore related applications</h2><div className="topic-links">{industries.filter(i=>i.serviceSlugs.includes(slug)).map(i=><a href={'/industries/'+i.slug} key={i.slug}>{i.name} ↗</a>)}<a href="/case-studies">Published case studies ↗</a><a href="/process">Our engineering process ↗</a></div></section><ProjectInvitation/></ContentShell>}
